language: python

python:
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements/requirements.txt
  - pip install -e .

# command to run tests
script:
  # - pytest --pyargs src
  - coverage run --source=src -m pytest --pyargs src

after_success:
  - coveralls
